container:
    dockerfile: .cirrus_Dockerfile
    cpu: 6
    memory: 24G
    use_in_memory_disk: true

validate_with_source_task:
    submodule_checkout_script:
        - git submodule update --init --recursive
    check_gn_flags_script:
        - ./ungoogled-chromium/devutils/check_gn_flags.py -f flags.macos.gn
        - # Merge GN flags and verify again
        - cp ungoogled-chromium/flags.gn flags.merged.gn
        - cat flags.macos.gn >> flags.merged.gn
        - sort -o flags.merged.gn flags.merged.gn
        - ./ungoogled-chromium/devutils/check_gn_flags.py -f flags.merged.gn
    check_downloads_ini_script:
        - ./ungoogled-chromium/devutils/check_downloads_ini.py -d ungoogled-chromium/downloads.ini downloads.ini
    check_patch_files_script:
        - ./ungoogled-chromium/devutils/check_patch_files.py -p patches
    merge_patches_script:
        - ./ungoogled-chromium/utils/patches.py merge -p patches ungoogled-chromium/patches
    chromium_download_cache:
        folder: chromium_download_cache
        fingerprint_script: cat ungoogled-chromium/chromium_version.txt
        populate_script:
            - mkdir chromium_download_cache
            - ./ungoogled-chromium/utils/downloads.py retrieve -i ungoogled-chromium/downloads.ini -c chromium_download_cache
    unpack_source_script:
        - ./ungoogled-chromium/utils/downloads.py unpack --skip-unused -i ungoogled-chromium/downloads.ini -c chromium_download_cache chromium_src
    validate_patches_script:
        - ./ungoogled-chromium/devutils/validate_patches.py -l chromium_src -v -p patches -s patches/series

# vim: set expandtab shiftwidth=4 softtabstop=4:
