# x86-64 (Intel) specific dependencies not included in the main Chromium source archive

# Pre-built LLVM toolchain for convenience
[llvm]
version = 21.1.0
url = https://github.com/implicitfield/llvm-macos-buildbot/releases/download/%(version)s-x86-64/clang+llvm-%(version)s-x86-64-apple-darwin21.0.tar.xz
download_filename = clang+llvm-%(version)s-x86-64-apple-darwin21.0.tar.xz
strip_leading_dirs = clang+llvm-%(version)s-x86-64-apple-darwin21.0
sha512 = 12f8df0091cd1ee427afa31c710e9a52a20c2a0087537e98bb4033f650b7fc53a2f55ce5ed389f87103b9fefe7d42a4cb0e33b8daa6abffd54c8dcd1be4b6168
output_path = third_party/llvm-build/Release+Asserts

[nodejs]
version = 24.12.0
url = https://nodejs.org/dist/v%(version)s/node-v%(version)s-darwin-x64.tar.xz
download_filename = node-v%(version)s-darwin-x64.tar.xz
strip_leading_dirs = node-v%(version)s-darwin-x64
sha512 = 3c1d16659764852555b0e23063e75c2fe64b7423d817093c5215a712ef6e16869279d78ccc85ed98d45694c333ad941c6fff289337ed6af869b18880972d0998
output_path = third_party/node/mac/node-darwin-x64

[rust]
version = 2025-12-03
url = https://static.rust-lang.org/dist/%(version)s/rust-nightly-x86_64-apple-darwin.tar.xz
download_filename = rust-nightly-%(version)s-x86_64-apple-darwin.tar.xz
output_path = third_party/rust-toolchain
strip_leading_dirs = rust-nightly-x86_64-apple-darwin
